[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = stlink
monitor_speed = 115200
src_filter = +<stm32_main.cpp> ; Hanya compile file ini untuk env bluepill
; Tambahan flags untuk mengatasi error upload pada chip clone (CKS32/GD32)
upload_flags =
    -c
    set CPUTAPID 0x2ba01477
lib_deps = marcoschwartz/LiquidCrystal_I2C@^1.1.4

; --- Konfigurasi untuk ESP32 (NodeMCU) ---
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
src_filter = +<esp32_main.cpp> ; Hanya compile file ini untuk env esp32dev
lib_deps = marcoschwartz/LiquidCrystal_I2C@^1.1.4